# Generated by Django 3.0 on 2019-12-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.DateField(auto_now=True),
        ),
    ]
