# Generated by Django 3.0 on 2019-12-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image_profile',
            field=models.ImageField(blank=True, default='default.jpeg', upload_to='uploads/image_profile'),
        ),
    ]
